version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "8080:15672"
      - "5672:5672"
    environment:
      - "RABBITMQ_DEFAULT_VHOST=service"

  web:
    build: .
    container_name: web
    command: bin/service
    depends_on:
      - mongodb
      - rabbitmq

